# Generated by Django 3.2.23 on 2024-01-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woohapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='unique_invite_code',
            field=models.CharField(default='GYVT6D', max_length=6, unique=True),
        ),
    ]
