# Generated by Django 3.2.23 on 2024-01-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woohapp', '0002_alter_myuser_unique_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='unique_invite_code',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
