# Generated by Django 3.2.23 on 2024-01-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woohapp', '0003_auto_20240104_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='hobbie_one',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='hobbie_three',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='hobbie_two',
        ),
        migrations.AddField(
            model_name='myuser',
            name='about_you',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.CharField(default=18, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='hobbies',
            field=models.ManyToManyField(to='woohapp.Hobby'),
        ),
    ]
