# Generated by Django 3.2.23 on 2024-01-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woohapp', '0004_auto_20240105_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='about_you',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
