# Generated by Django 3.2.23 on 2024-01-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('woohapp', '0005_auto_20240106_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default='default_images/default.jpg', upload_to='profile_pictures/', blank=True,
                                    null=True),
    ),
    ]

