# Generated by Django 3.2.23 on 2024-01-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woohapp', '0006_myuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='myuser',
            name='hobbies',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
