# Generated by Django 3.2.23 on 2024-01-13 09:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woohapp', '0007_auto_20240112_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='profile_picture'),
            preserve_default=False,
        ),
    ]
